language: node_js
sudo: false
node_js:
    - '12.0.0'

cache:
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn lint --cache
    - yarn build:lib
    - yarn build:app
    - yarn test --coverage
