import { ElementRef, EventEmitter, NgZone, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { DynamicHeightOptions } from '../interfaces/table-builder.internal';
export declare class AutoHeightDirective implements OnInit, OnChanges, OnDestroy {
    private readonly element;
    readonly ngZone: NgZone;
    private static readonly DEFAULT_VALUE;
    private static readonly HEAD_TOP;
    private static readonly DELAY;
    headerHeight: number;
    footerHeight: number;
    autoHeight: Partial<DynamicHeightOptions>;
    recalculatedHeight: EventEmitter<void>;
    private useOnlyAutoViewPort;
    private isDirtyCheck;
    private taskId;
    private handler;
    constructor(element: ElementRef, ngZone: NgZone);
    private readonly height;
    private readonly canCalculated;
    private readonly style;
    private readonly isEmptyParentHeight;
    private readonly parentOffsetHeight;
    private readonly currentElement;
    private readonly childElement;
    private readonly rootCurrentElement;
    private readonly columnHeight;
    private readonly autoViewHeight;
    private static getStyle;
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    recalculateTableSize(): void;
    calculateHeight(): void;
    markForCheck(): void;
    private getDefaultHeight;
    private getHeightByParent;
    private getHeightByViewPort;
    private setHeightByParent;
}
